# .streamlit/secrets.toml

[passwords]
# Follow the rule: username = "password"
jerome = "jerome"
guillaume = "guillaume"
dsia = "dsia"
mllm = "mllm"
nemo = "nemo"
celine = "celine"
lucas = "lucas"
laurent = "laurent"
diese = "diese"
