#  Copyright (c) 2024, RTE (https://www.rte-france.com)
#  See AUTHORS.txt
#  SPDX-License-Identifier: MPL-2.0
#  This file is part of BERTrend.

# Embedding service parameters
[embedding_service]
# Indicates if BERTrend shall use a local embedding service (run by BERTrend) or if the embedding service
# is delegated to an external service. If set to false, the other properties shall be set properly.
# It is generally more efficient to use a dedicated service for embeddings.
use_local = true
model_name = "OrdalieTech/Solon-embeddings-large-0.1"
url = "https://10.132.5.44:6464"
embedding_dtypes = ["float32", "float16", "bfloat16"]
embedding_batch_size = 2048
embedding_max_seq_length = 512

# LLM service parameters
[llm_service]
# Specifies here the information about the LLM to be used to benefit from some LLM features such as
# improved topic description and topic analysis over time
# If empty, these features will not be available
# BERTrend can use any kind of openai-compatible deployment such as
# - local LLM deployed with VLLM or similar libraries
# - the official OpenAI endpoint
# - models deployed on Azure cloud
api_key = "$AZURE_SE_WATTELSE_OPENAI_API_KEY_DEV"
endpoint = "$AZURE_SE_WATTELSE_OPENAI_ENDPOINT_DEV"
model = "$AZURE_SE_WATTELSE_OPENAI_DEFAULT_MODEL_NAME_DEV"
temperature = 0.1
max_output_tokens = 2048
system_prompt = "You are a helpful assistant, skilled in detailing topic evolution over time for the detection of emerging trends and signals."